// <auto-generated />
using System;
using GeradorRelatoriosWeb.Infra.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeradorRelatoriosWeb.Infra.Dados.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20190709171058_menu")]
    partial class menu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PaginasAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnName("Controller");

                    b.Property<bool>("Desativado")
                        .HasColumnName("Desativado");

                    b.Property<string>("NomeMenu")
                        .IsRequired()
                        .HasColumnName("NomeMenu");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnName("View");

                    b.HasKey("Id");

                    b.ToTable("PaginasAcessos");
                });

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PerfilAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("PerfisAcesso");
                });

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PerfilPaginas", b =>
                {
                    b.Property<Guid>("IdPagina");

                    b.Property<Guid>("IdPerfil");

                    b.HasKey("IdPagina", "IdPerfil");

                    b.HasIndex("IdPerfil");

                    b.ToTable("PerfilPaginas");
                });

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email");

                    b.Property<Guid>("IdPerfil")
                        .HasColumnName("IdPerfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("Senha");

                    b.Property<int>("Status")
                        .HasColumnName("Status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("Token");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PerfilPaginas", b =>
                {
                    b.HasOne("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PaginasAcesso", "Pagina")
                        .WithMany()
                        .HasForeignKey("IdPagina")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PerfilAcesso", "Perfil")
                        .WithMany("Paginas")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.Usuario", b =>
                {
                    b.HasOne("GeradorRelatoriosWeb.Dominio.Entidades.Sistema.PerfilAcesso", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
